name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build all apps
        run: npx nx run-many --target=build --all --prod

      - name: List build output
        run: ls -R dist

      - name: Verify shell output
        run: |
          if [ -d "dist/apps/shell" ]; then
            echo "Shell build output exists."
          else
            echo "Shell build output does NOT exist."
            exit 1
          fi

      - name: Clone gh-pages branch
        run: |
          git config --global user.name "Avinash219"
          git config --global user.email "avinash.dev21987@gmail.com"
          git clone https://github.com/${{ github.repository }}.git gh-pages-branch
          cd gh-pages-branch
          git checkout gh-pages || git checkout --orphan gh-pages
          cd ..

      - name: List branches for debugging
        run: |
          cd gh-pages-branch
          git branch -a
          cd ..

      - name: Deploy shell to GitHub Pages root
        run: |
          rsync -av --delete dist/apps/shell/ gh-pages-branch/
          cd gh-pages-branch
          mkdir apps
          git add .

      - name: List build output
        run: git status

      - name: Verify shell output
        run: |
          git commit -m "Update Shell"
          git push -u origin gh-pages || true
          cd ..

      - name: Deploy other apps to their respective directories
        run: |
          for app in auth feed; do
            if [ -d dist/apps/$app ]; then
              mkdir -p gh-pages-branch/$app
              rsync -av --delete dist/apps/$app/ gh-pages-branch/$app/
              cd gh-pages-branch
              git add .
              git commit -m "Update $app"
              git pull origin gh-pages --rebase || true
              cd ..
            else
              echo "Directory dist/apps/$app does not exist. Skipping $app deployment."
            fi
          done

      - name: Push other apps to GitHub Pages
        run: |
          cd gh-pages-branch
          git push origin gh-pages
          cd ..
