name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # - name: Lint code
      # run: npm run lint

      # - name: Run tests
      #run: npm run test -- --no-watch --code-coverage

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          npm run build --prod
          npx angular-cli-ghpages --dir=dist/apps/shell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
