name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [shell, auth, feed, messaging, profile, projects] # List all your apps here

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build all apps
        run: npx nx run-many --target=build --all --prod

      - name: Deploy shell to GitHub Pages root
        if: matrix.app == 'shell'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --branch=gh-pages https://github.com/${{ github.repository }}.git gh-pages-branch
          rsync -av --delete dist/shell/ gh-pages-branch/
          cd gh-pages-branch
          git add .
          git commit -m "Update Shell"
          git push origin gh-pages

      - name: Deploy other apps to their respective directories
        if: matrix.app != 'shell'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --branch=gh-pages https://github.com/${{ github.repository }}.git gh-pages-branch
          mkdir -p gh-pages-branch/${{ matrix.app }}
          rsync -av --delete dist/${{ matrix.app }}/ gh-pages-branch/${{ matrix.app }}/
          cd gh-pages-branch
          git add .
          git commit -m "Update ${{ matrix.app }}"
          git push origin gh-pages
