name: Deploy NX Microapp to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build shell app
        run: npx nx run-many --target=build --all --parallel --prod # Replace 'build:shell' with the actual build command for your shell app

      - name: Create root deployment directory
        run: mkdir -p ./dist/root
        run: mkdir -p ./dist/root/apps

      - name: Copy shell app to root
        run: cp -r ./dist/apps/shell/* ./dist/root/

      - name: Copy other apps to root
        run: |
          cp -r ./dist/apps/feed ./dist/root/apps/feed
          cp -r ./dist/apps/messaging ./dist/root/apps/messaging
          cp -r ./dist/apps/profile ./dist/root/apps/profile
          cp -r ./dist/apps/projects ./dist/root/apps/projects

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/root # Replace with the path to your shell app's build output directory
