name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build all apps
        run: npx nx run-many --target=build --all --prod

      - name: List build output
        run: ls -R dist

      - name: Verify shell output
        run: |
          if [ -d "dist/apps/shell" ]; then
            echo "Shell build output exists."
          else
            echo "Shell build output does NOT exist."
            exit 1
          fi

      - name: Deploy shell to GitHub Pages root
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --branch=gh-pages https://github.com/${{ github.repository }}.git gh-pages-branch || git init gh-pages-branch
          cd gh-pages-branch
          git checkout gh-pages || git checkout -b gh-pages
          cd ..
          rsync -av --delete dist/apps/shell/ gh-pages-branch/
          cd gh-pages-branch
          git add .
          git commit -m "Update Shell"
          git push origin gh-page

      - name: Deploy other apps to their respective directories
        run: |
          for app in auth, feed, messaging, profile, projects; do
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git clone --branch=gh-pages https://github.com/${{ github.repository }}.git gh-pages-branch || git init gh-pages-branch
            cd gh-pages-branch
            git checkout gh-pages || git checkout -b gh-pages
            cd ..
            mkdir -p gh-pages-branch/$app
            rsync -av --delete dist/apps/$app/ gh-pages-branch/apps/$app/
            cd gh-pages-branch
            git add .
            git commit -m "Update $app"
            git push origin gh-pages
            cd ..
            rm -rf gh-pages-branch
          done
