name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # - name: Lint code
      #   run: npm run lint

      # - name: Run tests
      #   run: npm run test -- --no-watch --code-coverage

      - name: Build project
        run: npm run build -- --configuration=production --base-href=/social-tech-stack/ --outputPath=dist/apps/shell

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Configure Git
        run: |
          git config --global user.name "Avinash219"
          git config --global user.email "avinash.dev21987@gmail.com"
        shell: bash

      - name: List build outputs
        run: ls -R dist/apps/

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout -b gh-pages
          cp -r dist .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
