name: Deploy Affected Apps to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Nx globally
        run: npm install -g nx

      - name: Determine affected projects
        id: affected
        run: |
          set -e
          affected=$(npx nx show projects --affected --base=main~1 --head=main || echo "")
          if [ -z "$affected" ]; then
            echo "No affected projects found."
           else
            echo "Affected projects: $affected"
          fi

      - name: Build affected apps
        run: |
          npx nx affected -t build --configuration=production --base=main~1 --head=main --maxParallel=7
      - name: Deploy affected apps to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/apps/$app
